# Generated by Django 5.2.4 on 2025-08-15 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_todo_owner'),
        ('schedules', '0002_alter_personaldayschedule_owner'),
        ('teams', '0002_remove_team_user_team_remove_team_user_user_teamuser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team_User',
        ),
    ]
