# Generated by Django 5.2.4 on 2025-08-27 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_delete_team_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('priority', models.CharField(choices=[('critical', '매우 중요'), ('high', '중요'), ('medium', '보통'), ('low', '낮음'), ('minimal', '미미')], default='medium', max_length=20)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'ordering': ['-priority', 'enddate'],
            },
        ),
        migrations.DeleteModel(
            name='DevPhase',
        ),
    ]
