# Generated by Django 5.2.4 on 2025-10-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_milestone_delete_devphase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='priority',
            field=models.CharField(choices=[('critical', '최우선'), ('high', '중요'), ('medium', '보통'), ('low', '낮음'), ('minimal', '미미')], default='medium', max_length=20),
        ),
    ]
