# Generated by Django 5.2.4 on 2025-12-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_team_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='progress_mode',
            field=models.CharField(choices=[('manual', '수동 입력'), ('auto', 'TODO 기반 자동 계산')], default='auto', help_text='진행률 관리 방식: 수동 입력 또는 TODO 기반 자동 계산', max_length=20),
        ),
    ]
