# Generated by Django 5.2.4 on 2025-12-09 18:19

import django.db.models.deletion
import shares.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0006_alter_team_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='제목')),
                ('article', models.TextField(verbose_name='내용')),
                ('registered_date', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('upload_files', models.FileField(blank=True, null=True, upload_to=shares.models.get_file_path, verbose_name='파일')),
                ('filename', models.CharField(max_length=64, null=True, verbose_name='첨부파일명')),
                ('team', models.ForeignKey(help_text='게시물이 속한 팀 (필수)', on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='팀')),
                ('teamuser', models.ForeignKey(blank=True, help_text='작성자 정보 (탈퇴 시 NULL)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.teamuser', verbose_name='작성자')),
            ],
            options={
                'verbose_name': '게시물',
                'verbose_name_plural': '게시물',
                'db_table': '게시물',
            },
        ),
    ]
