# Generated by Django 5.2.4 on 2025-09-21 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0002_alter_post_options_remove_post_hits_post_filename_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '게시물', 'verbose_name_plural': '게시물'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='isTeams',
            new_name='team',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upload_images',
        ),
        migrations.AlterModelTable(
            name='post',
            table='게시물',
        ),
    ]
