# Generated by Django 4.1.3 on 2022-12-04 05:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mindmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posX', models.PositiveIntegerField()),
                ('posY', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('vote', models.PositiveSmallIntegerField(default=0)),
                ('mindmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindmaps.mindmap')),
            ],
        ),
        migrations.CreateModel(
            name='Node_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted', models.BooleanField(default=False)),
                ('Node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindmaps.node')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Node_Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to+', to='mindmaps.node')),
                ('mindmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindmaps.mindmap')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from+', to='mindmaps.node')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='next',
            field=models.ManyToManyField(blank=True, through='mindmaps.Node_Node', to='mindmaps.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='user',
            field=models.ManyToManyField(related_name='Nodes', through='mindmaps.Node_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('commented_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindmaps.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
