# Generated by Django 4.1.3 on 2022-12-08 22:11

from django.db import migrations, models
import django.db.models.deletion
import shares.models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '공지사항', 'verbose_name_plural': '공지사항'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='hits',
        ),
        migrations.AddField(
            model_name='post',
            name='filename',
            field=models.CharField(max_length=64, null=True, verbose_name='첨부파일명'),
        ),
        migrations.AddField(
            model_name='post',
            name='isTeams',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='팀'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='upload_files',
            field=models.FileField(blank=True, null=True, upload_to=shares.models.get_file_path, verbose_name='파일'),
        ),
        migrations.AddField(
            model_name='post',
            name='upload_images',
            field=models.FileField(blank=True, null=True, upload_to=shares.models.get_file_path, verbose_name='이미지파일'),
        ),
        migrations.AlterField(
            model_name='post',
            name='article',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterModelTable(
            name='post',
            table='공지사항',
        ),
    ]
