# Generated by Django 5.2.4 on 2025-10-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_nickname_alter_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': '이미 사용 중인 이메일입니다.'}, max_length=254, unique=True),
        ),
    ]
