# Generated by Django 4.1.2 on 2022-11-25 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('maxuser', models.PositiveIntegerField()),
                ('currentuser', models.PositiveIntegerField()),
                ('invitecode', models.CharField(max_length=16)),
                ('teampasswd', models.TextField()),
                ('introduction', models.TextField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Todo', models.TextField(blank=True, null=True)),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='joined_teams', through='teams.Team_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
