# Generated by Django 5.2.4 on 2025-08-15 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmaps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node_user',
            name='Node',
        ),
        migrations.RemoveField(
            model_name='node_user',
            name='User',
        ),
        migrations.CreateModel(
            name='NodeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='mindmaps.node')),
                ('mindmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindmaps.mindmap')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='mindmaps.node')),
            ],
        ),
        migrations.AlterField(
            model_name='node',
            name='next',
            field=models.ManyToManyField(blank=True, through='mindmaps.NodeConnection', to='mindmaps.node'),
        ),
        migrations.CreateModel(
            name='NodeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted', models.BooleanField(default=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindmaps.node')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='node',
            name='user',
            field=models.ManyToManyField(related_name='nodes', through='mindmaps.NodeUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Node_Node',
        ),
        migrations.DeleteModel(
            name='Node_User',
        ),
    ]
