# Generated by Django 5.2.4 on 2025-08-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmaps', '0002_remove_node_user_node_remove_node_user_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='recommendation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='recommended_users',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
