# Generated by Django 5.2.4 on 2025-08-25 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindmaps', '0003_node_recommendation_count_node_recommended_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='user',
        ),
        migrations.RemoveField(
            model_name='node',
            name='vote',
        ),
        migrations.DeleteModel(
            name='NodeUser',
        ),
    ]
