# Generated by Django 5.2.4 on 2025-10-03 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindmaps', '0004_remove_node_user_remove_node_vote_delete_nodeuser'),
        ('teams', '0005_alter_milestone_priority'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mindmap',
            unique_together={('team', 'title')},
        ),
    ]
