# Generated by Django 5.2.4 on 2025-11-24 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindmaps', '0005_alter_mindmap_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='댓글 작성자 (탈퇴 시 NULL)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mindmap_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
