# Generated by Django 4.1.3 on 2022-11-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
