# Generated by Django 5.2.4 on 2025-08-15 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='team',
        ),
    ]
