# Generated by Django 5.2.4 on 2025-08-29 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_todo_options_remove_todo_is_completed_and_more'),
        ('teams', '0004_milestone_delete_devphase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_set', to='teams.teamuser'),
        ),
    ]
