# Generated by Django 5.2.4 on 2025-11-24 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_refactor_status_to_is_completed'),
        ('teams', '0006_alter_team_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='TODO 담당자 (탈퇴 시 NULL, 미할당 상태로 변경)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todo_set', to='teams.teamuser'),
        ),
    ]
