# Generated by Django 5.2.4 on 2025-12-27 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_todo_assignee'),
        ('teams', '0007_add_progress_mode_to_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='milestone',
            field=models.ForeignKey(blank=True, help_text='연결된 마일스톤 (마일스톤 삭제 시 NULL, 연결 해제 상태로 변경)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='teams.milestone'),
        ),
    ]
