# Generated by Django 5.2.4 on 2025-08-15 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        ('teams', '0002_remove_team_user_team_remove_team_user_user_teamuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldayschedule',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.teamuser'),
        ),
    ]
