# Generated by Django 5.2.4 on 2025-08-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_personaldayschedule_owner'),
        ('teams', '0003_delete_team_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='personaldayschedule',
            unique_together={('date', 'owner')},
        ),
        migrations.AddField(
            model_name='personaldayschedule',
            name='available_hours',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='TeamDaySchedule',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_0',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_1',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_10',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_11',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_12',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_13',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_14',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_15',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_16',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_17',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_18',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_19',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_2',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_20',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_21',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_22',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_23',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_3',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_4',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_5',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_6',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_7',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_8',
        ),
        migrations.RemoveField(
            model_name='personaldayschedule',
            name='time_9',
        ),
    ]
