# Generated by Django 4.1.3 on 2022-12-04 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamDaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_0', models.PositiveIntegerField(default=0)),
                ('time_1', models.PositiveIntegerField(default=0)),
                ('time_2', models.PositiveIntegerField(default=0)),
                ('time_3', models.PositiveIntegerField(default=0)),
                ('time_4', models.PositiveIntegerField(default=0)),
                ('time_5', models.PositiveIntegerField(default=0)),
                ('time_6', models.PositiveIntegerField(default=0)),
                ('time_7', models.PositiveIntegerField(default=0)),
                ('time_8', models.PositiveIntegerField(default=0)),
                ('time_9', models.PositiveIntegerField(default=0)),
                ('time_10', models.PositiveIntegerField(default=0)),
                ('time_11', models.PositiveIntegerField(default=0)),
                ('time_12', models.PositiveIntegerField(default=0)),
                ('time_13', models.PositiveIntegerField(default=0)),
                ('time_14', models.PositiveIntegerField(default=0)),
                ('time_15', models.PositiveIntegerField(default=0)),
                ('time_16', models.PositiveIntegerField(default=0)),
                ('time_17', models.PositiveIntegerField(default=0)),
                ('time_18', models.PositiveIntegerField(default=0)),
                ('time_19', models.PositiveIntegerField(default=0)),
                ('time_20', models.PositiveIntegerField(default=0)),
                ('time_21', models.PositiveIntegerField(default=0)),
                ('time_22', models.PositiveIntegerField(default=0)),
                ('time_23', models.PositiveIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_0', models.BooleanField(default=False)),
                ('time_1', models.BooleanField(default=False)),
                ('time_2', models.BooleanField(default=False)),
                ('time_3', models.BooleanField(default=False)),
                ('time_4', models.BooleanField(default=False)),
                ('time_5', models.BooleanField(default=False)),
                ('time_6', models.BooleanField(default=False)),
                ('time_7', models.BooleanField(default=False)),
                ('time_8', models.BooleanField(default=False)),
                ('time_9', models.BooleanField(default=False)),
                ('time_10', models.BooleanField(default=False)),
                ('time_11', models.BooleanField(default=False)),
                ('time_12', models.BooleanField(default=False)),
                ('time_13', models.BooleanField(default=False)),
                ('time_14', models.BooleanField(default=False)),
                ('time_15', models.BooleanField(default=False)),
                ('time_16', models.BooleanField(default=False)),
                ('time_17', models.BooleanField(default=False)),
                ('time_18', models.BooleanField(default=False)),
                ('time_19', models.BooleanField(default=False)),
                ('time_20', models.BooleanField(default=False)),
                ('time_21', models.BooleanField(default=False)),
                ('time_22', models.BooleanField(default=False)),
                ('time_23', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team_user')),
            ],
        ),
    ]
